// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yynkynftcaeadmyntwar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bmt5bmZ0Y2FlYWRteW50d2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTIxNjcsImV4cCI6MjA3MDQyODE2N30.4mdo-Cso7SPzi0d3gKxFhGWqR2kqyl3apyHRd350yOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});